version: 2

workflows:
  version: 2
  build:
    jobs:
      - install
      - lint:
          requires:
            - install
      - build:
          requires:
            - install
      - deploy:
          requires:
            - install
            - lint
            - build
          filters:
            branches:
              only:
                - master
                - dev
                - intents-fix

jobs:
  install:
    working_directory: ~/stockflux
    docker:
      - image: circleci/node:10.15.1
    steps:
      - checkout:
          path: ~/stockflux
      - run:
          name: Root package install
          command: npm ci
      - run:
          name: Bootstrap Packages
          command: npm run bootstrap
      - persist_to_workspace:
          root: ~/stockflux
          paths: .

  lint:
    working_directory: ~/stockflux
    docker:
      - image: circleci/node:10.15.1
    steps:
      - attach_workspace:
          at: ~/stockflux
      - run:
          name: Lint *.js files
          command: npm run lint

  build:
    working_directory: ~/stockflux
    docker:
      - image: circleci/node:10.15.1
    steps:
      - attach_workspace:
          at: ~/stockflux
      - run:
          name: Build Packages
          command: npm run build
      - persist_to_workspace:
          root: ~/stockflux
          paths: .

  deploy:
    working_directory: ~/stockflux
    docker:
      - image: circleci/python:3.7.2
    steps:
      - attach_workspace:
          at: ~/stockflux
      - add_ssh_keys:
          fingerprints:
            - 'e1:6c:ab:38:9e:8f:ed:f1:60:4a:c7:b1:23:33:0c:07'
            - '16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48' # GitHub RSA
            - 'ad:1c:08:a4:40:e3:6f:9c:f5:66:26:5d:4b:33:5d:8c' # GitHub DSA
      - run:
          name: Add GitHub SSH fingerprints to known hosts
          command: |
            # https://serverfault.com/questions/447028/non-interactive-git-clone-ssh-fingerprint-prompt
            # Grabbed GitHub's public key by running ssh-keyscan github.com
            # locally and directing it to the github_key file. Adding this key
            # to known hosts (creating it if it doesn't exist) prevents the
            # prompt that warns about the authenticity of the host when trying
            # to push tags, that causes the build to hang until it times out.
            cd ~/stockflux/.circleci
            mkdir -p ~/.ssh
            touch ~/.ssh/known_hosts
            echo $(cat github_key) >> ~/.ssh/known_hosts
      - run:
          name: Determine version
          command: |
            cd ~/stockflux
            STOCKFLUX_VERSION=$(cat package.json | jq -r '.version')
            echo "${STOCKFLUX_VERSION}.${CIRCLE_BUILD_NUM}" > version
      - run:
          name: Install AWS CLI
          command: pip install awscli --user --upgrade
      - run:
          name: Upload Artifacts to S3
          command: |
            cd ~/stockflux
            STOCKFLUX_VERSION=$(cat version)
            BUCKET="stockflux-public--$CIRCLE_BRANCH"
            ~/.local/bin/aws s3 sync \
              packages/stockflux-chart/build \
              "s3://$BUCKET/artifacts/stockflux-chart/$STOCKFLUX_VERSION/" \
              --delete
            ~/.local/bin/aws s3 sync \
              packages/stockflux-container/build \
              "s3://$BUCKET/artifacts/stockflux-container/$STOCKFLUX_VERSION/" \
              --delete
            ~/.local/bin/aws s3 sync \
              packages/stockflux-news/build \
              "s3://$BUCKET/artifacts/stockflux-news/$STOCKFLUX_VERSION/" \
              --delete
            ~/.local/bin/aws s3 sync \
              packages/stockflux-watchlist/build \
              "s3://$BUCKET/artifacts/stockflux-watchlist/$STOCKFLUX_VERSION/" \
              --delete
            ~/.local/bin/aws s3 sync \
              packages/stockflux-launcher/build \
              "s3://$BUCKET/artifacts/stockflux-launcher/$STOCKFLUX_VERSION/" \
              --delete
      - run:
          name: Tag GitHub with new version
          command: |
            STOCKFLUX_VERSION=$(cat ~/stockflux/version)
            rm ~/stockflux/version
            git tag "$STOCKFLUX_VERSION"
            git push --tags
